// apps/portal/src/components/ui/input.tsx
import * as React from "react";
import { cn } from "@/lib/cn";

const Input = React.forwardRef<HTMLInputElement, React.ComponentProps<"input">>(
  ({ className, type, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(
          "flex h-11 w-full border-b border-ink/30 bg-transparent px-0 py-2 font-mono text-sm text-ink outline-none transition-colors placeholder:text-ink/60 focus:border-ink disabled:cursor-not-allowed disabled:opacity-40",
          className
        )}
        ref={ref}
        {...props}
      />
    );
  }
);
Input.displayName = "Input";

export { Input };

// apps/admin/src/components/ui/input/Input.vue
<script setup lang="ts">
import type { HTMLAttributes, InputHTMLAttributes } from "vue";
import { useVModel } from "@vueuse/core";
import { cn } from "@/lib/utils";
const props = defineProps<{ defaultValue?: string | number; modelValue?: string | number; class?: HTMLAttributes["class"]; type?: InputHTMLAttributes["type"]; placeholder?: string }>();
const emits = defineEmits<{ "update:modelValue": [payload: string | number] }>();
const modelValue = useVModel(props, "modelValue", emits, { passive: true, defaultValue: props.defaultValue });
</script>
<template><input v-model="modelValue" :type="type" :placeholder="placeholder" :class="cn('flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50', $props.class)" /></template>
